# Generated by Django 3.1.5 on 2021-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('First_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateField()),
                ('Location', models.CharField(max_length=25)),
            ],
        ),
    ]
